# Custom shutdown hook timeout in milliseconds (should be larger than Hystrix command execution timeout
# to ensure that the shutdown does not happen earlier than the last request is completed/fallback by hystrix
shutdownHook:
  timeoutMillis: 10000

# Custom configuration for CSRF cookie root domain
# since we have lots of microservices sharing the sub-domain
# defining the CSRF cookie with root domain ensure it could shared with all the sub-domain
csrf:
  cookie:
    root:
      domain: pcf.manulife.com
#      domain: localhost

# Custom configuration for redirecting after login complete, for example redirect back to Angular website
login:
  complete:
    redirect:
      url: https://demo-angular-app.apps.sea.preview.pcf.manulife.com
#      url: http://localhost:4200

# Custom configuration for configuring list of CORS allowed origins
# for example, add the Angular website domain to allow cross-origin-request via ajax
cors:
  allowed:
    origins: https://demo-angular-app.apps.sea.preview.pcf.manulife.com
#    origins: http://localhost:4200